#!/usr/bin/with-contenv bash
# shellcheck shell=bash

echo -e "0 3 * * * blocklist-update 2>&1" >> /tmp/crontab.list

echo "Set crontab to system..."
crontab /tmp/crontab.list
echo "Current crontab is:"
crontab -l
rm -f /tmp/crontab.list