#!/usr/bin/with-contenv bash
# shellcheck shell=bash

PORT=$(jq '.["rpc-port"]' /config/settings.json)

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost ${PORT:-9091}" \
    s6-setuidgid tr /usr/bin/transmission-daemon \
    -g /config -f
