#!/usr/bin/with-contenv bash
# shellcheck shell=bash

function __mkdir {

    DOWNLOAD_DIR=${DOWNLOAD_DIR:-/downloads}

    UMASK=${UMASK:-022}
    umask ${UMASK}

    echo "Make some folders..."

    if [ ! -d ${DOWNLOAD_DIR} ]; then
        mkdir ${DOWNLOAD_DIR}
    fi

    if [ ! -d ${DOWNLOAD_DIR}/complete ]; then
        mkdir ${DOWNLOAD_DIR}/complete
    fi

    if [ ! -d ${DOWNLOAD_DIR}/incomplete ]; then
        mkdir ${DOWNLOAD_DIR}/incomplete
    fi

    if [ ! -d /config ]; then
        mkdir /config
    fi

    if [ ! -d /watch ]; then
        mkdir /watch
    fi

}

__mkdir 2>&1 | sed "s#^#cont-init: info: $(realpath $0): \1#g"