#!/usr/bin/with-contenv bash
# shellcheck shell=bash

function __config {

    DOWNLOAD_DIR=${DOWNLOAD_DIR:-/download}

    UMASK=${UMASK:-022}
    umask ${UMASK}

    if [[ ! -f /config/settings.json ]]; then
        cp /defaults/settings.json /config/settings.json
    fi

    if [[ -n "$USER" ]] && [[ -n "$PASS" ]]; then
        sed -i '/rpc-authentication-required/c\    "rpc-authentication-required": true,' /config/settings.json
        sed -i "/rpc-username/c\    \"rpc-username\": \"$USER\"," /config/settings.json
        sed -i "/rpc-password/c\    \"rpc-password\": \"$PASS\"," /config/settings.json
    else
        sed -i '/rpc-authentication-required/c\    "rpc-authentication-required": false,' /config/settings.json
        sed -i "/rpc-username/c\    \"rpc-username\": \"$USER\"," /config/settings.json
        sed -i "/rpc-password/c\    \"rpc-password\": \"$PASS\"," /config/settings.json
    fi

    if [[ -n "$WHITELIST" ]]; then
        sed -i '/rpc-whitelist-enabled/c\    "rpc-whitelist-enabled": true,' /config/settings.json
        sed -i "/\"rpc-whitelist\"/c\    \"rpc-whitelist\": \"$WHITELIST\"," /config/settings.json
    else
        sed -i '/rpc-whitelist-enabled/c\    "rpc-whitelist-enabled": false,' /config/settings.json
        sed -i "/\"rpc-whitelist\"/c\    \"rpc-whitelist\": \"$WHITELIST\"," /config/settings.json
    fi

    if [[ -n "$HOST_WHITELIST" ]]; then
        sed -i '/rpc-host-whitelist-enabled/c\    "rpc-host-whitelist-enabled": true,' /config/settings.json
        sed -i "/\"rpc-host-whitelist\"/c\    \"rpc-host-whitelist\": \"$HOST_WHITELIST\"," /config/settings.json
    else
        sed -i '/rpc-host-whitelist-enabled/c\    "rpc-host-whitelist-enabled": false,' /config/settings.json
        sed -i "/\"rpc-host-whitelist\"/c\    \"rpc-host-whitelist\": \"$HOST_WHITELIST\"," /config/settings.json
    fi

    if [[ -n "${PEERPORT}" ]]; then
        sed -i "/\"peer-port\"/c\    \"peer-port\": ${PEERPORT}," /config/settings.json
        sed -i '/peer-port-random-on-start/c\     "peer-port-random-on-start": false,' /config/settings.json
    fi

    if [ -n "${DOWNLOAD_DIR}" ]; then
        sed -i "/\"download-dir\"/c\    \"download-dir\": \"$DOWNLOAD_DIR\"," /config/settings.json
        sed -i "/\"incomplete-dir\"/c\    \"incomplete-dir\": \"$DOWNLOAD_DIR/incomplete\"," /config/settings.json
    fi

}

__config 2>&1 | sed "s#^#cont-init: info: $(realpath $0): \1#g"
