name: Build transmission image

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"

jobs:
  v4:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master

      - 
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/transmission

      - 
        name: Rename version
        run: |
          mkdir version
          curl -sL "http://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz" | tar -xz -C version
          TR_VERSION=$(awk '/^P:transmission$/,/V:/' version/APKINDEX | sed -n 2p | sed 's/^V://')
          echo "${TR_VERSION}"
          echo "tr_version=${TR_VERSION}" >> $GITHUB_ENV

      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - 
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - 
        name: Build transmission image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          platforms: |
            linux/amd64
            linux/arm64/v8
          push: true
          build-args: |
            TRANSMISSION_VERSION=${{ env.tr_version }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
             ${{ secrets.DOCKER_USERNAME }}/transmission:${{ env.tr_version }}
             ${{ secrets.DOCKER_USERNAME }}/transmission:v4
             ${{ secrets.DOCKER_USERNAME }}/transmission:latest

  v3:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master

      - 
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/transmission

      - 
        name: Rename version
        run: |
          mkdir version
          curl -sL "http://dl-cdn.alpinelinux.org/alpine/v3.17/community/x86_64/APKINDEX.tar.gz" | tar -xz -C version
          TR_VERSION=$(awk '/^P:transmission$/,/V:/' version/APKINDEX | sed -n 2p | sed 's/^V://')
          echo "${TR_VERSION}"
          echo "tr_version=${TR_VERSION}" >> $GITHUB_ENV

      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - 
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - 
        name: Build transmission image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: v3.Dockerfile
          platforms: |
            linux/amd64
            linux/arm64/v8
            linux/arm/v7
          push: true
          build-args: |
            TRANSMISSION_VERSION=${{ env.tr_version }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
             ${{ secrets.DOCKER_USERNAME }}/transmission:${{ env.tr_version }}
             ${{ secrets.DOCKER_USERNAME }}/transmission:v3